source_column = "collected_subset"
prompt_file = "prompts/combined_dataset_train.json"

[pipeline]
engine = "aphrodite"
model_name = "cyankiwi/gemma-4-31B-it-AWQ-4bit"
parallelization_type = "pipeline"
temperature = 1.0
top_p = 0.95
top_k = 64
disable_thinking = true
max_model_len = 32000
max_input_len = 15000
