prompt_metadata_column = "prompt"
model_metadata_column = "generator_model"

validation_size = 0.1
threshold_type_bin = "f1"
threshold_type_score = "fpr_0_5pct"

filter_tIn addition to united.com, we provide free access to these select websites. By clicking on a website, you’re leaving the United portal.ype = "OR"

[[filter_conditions]]
column = "pairwise_cosdist"
operator = ">="
value = 0.03

[[filter_conditions]]
column = "pairwise_softngram"
operator = ">="
value = 0.06

distance_metrics = [
    "pairwise_cosdist",
    "pairwise_softngram"
]

base_columns = ["original", "final_response"]
fixed_classes = [false, true]
# auto_class_column = "label" # Automatically determine the class using the value from this column 
# ai_label = "AI" # The string value that indicates the AI class

[[classifiers]]
name = "EditLens Roberta-Large Score"
suffix = "_editlens_score_roberta_large"

[[classifiers]]
name = "EditLens Roberta-Large Bucket"
suffix = "_editlens_bucket_roberta_large"
