prompt_metadata_column = "prompt"
model_metadata_column = "generator_model"

base_model = "FacebookAI/roberta-large"
checkpoint = "pangram/editlens_roberta-large"
max_length = 512
batch_size = 24

# Splits the test set into a small validation set to determine classification thresholds
validation_size = 0.1
threshold_type_bin = "f1"
threshold_type_score = "fpr0.5"
manual_threshold_score = -1.0
manual_threshold_bin = -1.0

# If the distance is below the lower bound, the row will be dropped
distance_metric_filter_type = "AND"
distance_metrics_lower_bounds = [0.03, 0.06]
distance_metrics = [
    "pairwise_cosdist_original_final_response",
    "pairwise_softngram_original_final_response"
]