# Optional: dataset prefix (e.g. Hugging Face username or organization and corpus prefix)
dataset_prefix = "G-reen/cc-2021-"

# Dataset stage names (prepended by dataset_prefix)
raw_dataset = "raw-sharded"
pre_filter_dataset = "processed"
post_filter_dataset = "filtered"
gen_dataset = "rewritten"
stat_dataset = "stat"
eval_dataset = "eval"

# Engine Virtual Environment Paths (Defaults to .vllm and .aphrodite)
# vllm_venv_path = ".vllm"
# aphrodite_venv_path = ".aphrodite"
