source_column = "collected_subset"
prompt_file = "prompts/combined_dataset_test.json"

[pipeline]
engine = "vllm"
model_name = "nvidia/Gemma-4-31B-IT-NVFP4"
parallelization_type = "pipeline"
temperature = 1.0
top_p = 0.95
top_k = 64
disable_thinking = true
max_model_len = 32000
max_input_len = 15000
