source_column = "collected_subset"
prompt_file = "prompts/combined_dataset_test.json"

[pipeline]
engine = "aphrodite"
model_name = "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"
parallelization_type = "data"
temperature = 1.25
top_p = 1.0
top_k = -1
top_a = 0.1
xtc = 0.3
nsigma = 1.5
disable_thinking = false
presence_penalty = 1.5
max_model_len = 32000
max_input_len = 15000