source_column = "collected_subset"
prompt_file = "prompts/combined_dataset_test.json"

[pipeline]
engine = "vllm"
model_name = "mistralai/Mistral-Small-4-119B-2603-NVFP4"
parallelization_type = "pipeline"
temperature = 0.7
disable_thinking = false
max_model_len = 32000
max_input_len = 15000

tokenizer_mode = "mistral"
config_format = "mistral"
load_format = "mistral"
