num_samples = 50000
source_column = "collected_subset_original_final_response"
prompt_file = "prompts/combined_dataset_test.json"

[pipeline]
engine = "aphrodite"
model_name = "Qwen/Qwen3-8B-AWQ"
temperature = 1.25
top_p = 1.0
top_k = -1
top_a = 0.1
xtc = 0.3
nsigma = 1.5
disable_thinking = true
presence_penalty = 1.5
max_model_len = 32000
max_input_tokens = 15000